name: Visual Studio C++ Build with vcpkg

on: [push] # Trigger the workflow on every push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'
      
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install --triplet x64-windows
          .\vcpkg\vcpkg.exe install curl
          .\vcpkg\vcpkg.exe install cpr
          .\vcpkg\vcpkg.exe install nlohmann-json
          .\vcpkg\vcpkg.exe integrate install
      
      - name: Build
        run: msbuild /p:Configuration=Debug /p:PlatformToolset=v142 /p:Platform=x86 /p:CppStandard=17 ./ShopSmart/ShopSmart.sln
