name: Visual Studio C++ Build with vcpkg

on: [push] # Trigger the workflow on every push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'
      
      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install --triplet x64-windows
          .\vcpkg install curl
          .\vcpkg install cpr
          .\vcpkg install sfml
          .\vcpkg install imgui
          .\vcpkg install imgui-sfml
          .\vcpkg install nlohmann
      
      - name: Build
        run: msbuild /p:Configuration=Debug /m /p:Platform=x86 ShopSmart.sln
