name: Visual Studio C++ Tests

on: [push] # Trigger the workflow on every push

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest' # Or specify a specific version of Visual Studio
      
      - name: Build
        run: msbuild /p:Configuration=Debug /m /p:Platform=x64 ShopSmart.sln
      
      - name: Run tests
        run: Debug\YourApp.exe
